services:
  app:
    container_name: vision-x-dev-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./build:/app/build
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

networks:
  vision-x-dev-network:
    name: vision-x-dev-network