version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./build:/app/build
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
