services:
  app:
    container_name: vision-x-prod-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./build:/app/build
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

networks:
  vision-x-dev-network:
    name: vision-x-prod-network