name: Deploy Workflow

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Deploy to Development Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DEV_SERVER_HOST }}
        username: ${{ secrets.DEV_SERVER_USER }}
        password: ${{ secrets.DEV_SERVER_PASSWORD }}
        port: 22
        script: |
          cd /path/to/project/on/dev
          git pull origin dev
          docker-compose -f docker-compose-dev.yml down
          docker-compose -f docker-compose-dev.yml up --build -d

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.PROD_SERVER_HOST }}
        username: ${{ secrets.PROD_SERVER_USER }}
        password: ${{ secrets.PROD_SERVER_PASSWORD }}
        port: 22
        script: |
          cd /path/to/project/on/prod
          git pull origin main
          docker-compose -f docker-compose-prod.yml down
          docker-compose -f docker-compose-prod.yml up --build -d
